import { User, Patient, Appointment, ToothDiagnosis, Referral } from './types'

// ==================== MOCK USERS ====================
export const mockUsers: User[] = [
  {
    id: 'user-admin-1',
    name: 'Carolina Mendoza',
    email: 'admin@marfilstetic.com',
    password: 'admin123',
    role: 'admin',
    specialty: 'Administración',
  },
  {
    id: 'user-doctor-1',
    name: 'Dra. Geraldine Caballero Licas',
    email: 'doctor@marfilstetic.com',
    password: 'doctor123',
    role: 'doctor',
    specialty: 'Odontología Estética',
  },
  {
    id: 'user-technician-1',
    name: 'Téc. Marfil Stetic 2',
    email: 'tecnico@marfilstetic.com',
    password: 'tecnico123',
    role: 'technician',
    specialty: 'Prótesis Dental',
  },
  {
    id: 'user-technician-2',
    name: 'Téc. Marfil Stetic 1',
    email: 'tecnico2@marfilstetic.com',
    password: 'tecnico123',
    role: 'technician',
    specialty: 'Ortodoncia',
  },
]

// ==================== MOCK PATIENTS ====================
export const mockPatients: Patient[] = [
  {
    id: 'patient-1',
    name: 'Isabella Ramírez Torres',
    email: 'isabella.r@email.com',
    phone: '+51 987 654 321',
    dni: '45678901',
    birthDate: '1992-03-15',
    address: 'Av. Larco 1234, Miraflores',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'patient-2',
    name: 'Carlos Mendoza Vega',
    email: 'carlos.m@email.com',
    phone: '+51 912 345 678',
    dni: '47890123',
    birthDate: '1988-07-22',
    address: 'Calle San Isidro 567',
    createdAt: '2025-01-15T14:30:00Z',
  },
  {
    id: 'patient-3',
    name: 'Lucía Fernández Díaz',
    email: 'lucia.f@email.com',
    phone: '+51 945 678 901',
    dni: '50123456',
    birthDate: '1995-11-08',
    address: 'Jr. Pardo 890, San Borja',
    createdAt: '2025-02-01T09:15:00Z',
  },
  {
    id: 'patient-4',
    name: 'André Castillo Ríos',
    email: 'andre.c@email.com',
    phone: '+51 923 456 789',
    dni: '48901234',
    birthDate: '1990-05-30',
    address: 'Av. Benavides 321, Surco',
    createdAt: '2025-02-05T16:45:00Z',
  },
  {
    id: 'patient-5',
    name: 'Valentina Rojas Poma',
    email: 'valentina.r@email.com',
    phone: '+51 956 789 012',
    dni: '52345678',
    birthDate: '1998-09-12',
    address: 'Calle Libertad 456, La Molina',
    createdAt: '2025-02-10T11:00:00Z',
  },
]

// ==================== MOCK APPOINTMENTS ====================
export const mockAppointments: Appointment[] = [
  {
    id: 'appointment-1',
    patientId: 'patient-1',
    date: '2025-03-05',
    time: '09:00',
    reason: 'Revisión general y blanqueamiento',
    status: 'pending',
    createdAt: '2025-02-28T08:00:00Z',
  },
  {
    id: 'appointment-2',
    patientId: 'patient-2',
    date: '2025-03-05',
    time: '10:30',
    reason: 'Dolor en muela inferior derecha',
    status: 'pending',
    createdAt: '2025-02-28T09:00:00Z',
  },
  {
    id: 'appointment-3',
    patientId: 'patient-3',
    date: '2025-03-05',
    time: '12:00',
    reason: 'Consulta por carillas dentales',
    status: 'pending',
    createdAt: '2025-02-28T10:00:00Z',
  },
  {
    id: 'appointment-4',
    patientId: 'patient-4',
    date: '2025-03-05',
    time: '14:00',
    reason: 'Control de ortodoncia',
    status: 'pending',
    createdAt: '2025-03-01T08:00:00Z',
  },
  {
    id: 'appointment-5',
    patientId: 'patient-5',
    date: '2025-03-06',
    time: '09:30',
    reason: 'Limpieza dental profunda',
    status: 'pending',
    createdAt: '2025-03-01T09:00:00Z',
  },
  {
    id: 'appointment-6',
    patientId: 'patient-1',
    date: '2025-03-06',
    time: '11:00',
    reason: 'Seguimiento de blanqueamiento',
    status: 'pending',
    createdAt: '2025-03-02T08:00:00Z',
  },
]

// ==================== COMMON TREATMENTS ====================
export const commonTreatments = [
  'Blanqueamiento dental',
  'Carilla de porcelana',
  'Carilla de composite',
  'Implante dental',
  'Corona dental',
  'Obtención (empaste)',
  'Endodoncia',
  'Extracción',
  'Limpieza dental',
  'Ortodoncia fija',
  'Ortodoncia removible',
  'Provisión de prótesis',
  'Recontorneado gingival',
  'Bonding dental',
  'Reconstrucción dental',
  'Sellante dental',
  'Fluorización',
  'Curetaje dental',
]

// ==================== TOOTH MAP ====================
export const toothMap: { number: number; name: string; quadrant: string }[] = [
  // Upper Right (1-8)
  { number: 1, name: 'Tercer Molar', quadrant: 'Superior Derecho' },
  { number: 2, name: 'Segundo Molar', quadrant: 'Superior Derecho' },
  { number: 3, name: 'Primer Molar', quadrant: 'Superior Derecho' },
  { number: 4, name: 'Segundo Premolar', quadrant: 'Superior Derecho' },
  { number: 5, name: 'Primer Premolar', quadrant: 'Superior Derecho' },
  { number: 6, name: 'Canino', quadrant: 'Superior Derecho' },
  { number: 7, name: 'Incisivo Lateral', quadrant: 'Superior Derecho' },
  { number: 8, name: 'Incisivo Central', quadrant: 'Superior Derecho' },
  // Upper Left (9-16)
  { number: 9, name: 'Incisivo Central', quadrant: 'Superior Izquierdo' },
  { number: 10, name: 'Incisivo Lateral', quadrant: 'Superior Izquierdo' },
  { number: 11, name: 'Canino', quadrant: 'Superior Izquierdo' },
  { number: 12, name: 'Primer Premolar', quadrant: 'Superior Izquierdo' },
  { number: 13, name: 'Segundo Premolar', quadrant: 'Superior Izquierdo' },
  { number: 14, name: 'Primer Molar', quadrant: 'Superior Izquierdo' },
  { number: 15, name: 'Segundo Molar', quadrant: 'Superior Izquierdo' },
  { number: 16, name: 'Tercer Molar', quadrant: 'Superior Izquierdo' },
  // Lower Left (17-24)
  { number: 17, name: 'Tercer Molar', quadrant: 'Inferior Izquierdo' },
  { number: 18, name: 'Segundo Molar', quadrant: 'Inferior Izquierdo' },
  { number: 19, name: 'Primer Molar', quadrant: 'Inferior Izquierdo' },
  { number: 20, name: 'Segundo Premolar', quadrant: 'Inferior Izquierdo' },
  { number: 21, name: 'Primer Premolar', quadrant: 'Inferior Izquierdo' },
  { number: 22, name: 'Canino', quadrant: 'Inferior Izquierdo' },
  { number: 23, name: 'Incisivo Lateral', quadrant: 'Inferior Izquierdo' },
  { number: 24, name: 'Incisivo Central', quadrant: 'Inferior Izquierdo' },
  // Lower Right (25-32)
  { number: 25, name: 'Incisivo Central', quadrant: 'Inferior Derecho' },
  { number: 26, name: 'Incisivo Lateral', quadrant: 'Inferior Derecho' },
  { number: 27, name: 'Canino', quadrant: 'Inferior Derecho' },
  { number: 28, name: 'Primer Premolar', quadrant: 'Inferior Derecho' },
  { number: 29, name: 'Segundo Premolar', quadrant: 'Inferior Derecho' },
  { number: 30, name: 'Primer Molar', quadrant: 'Inferior Derecho' },
  { number: 31, name: 'Segundo Molar', quadrant: 'Inferior Derecho' },
  { number: 32, name: 'Tercer Molar', quadrant: 'Inferior Derecho' },
]
